#!/bin/bash
set -x 
txt() { cat<<EOF
Dear $1

Thank you for submission. Please note the following
next steps (taken from our CFP). If you have any
technical issues with the following (e.g. you are not
familiar with using Github) then please contact us and
we will do the following for you.

> 1) Our reply to you will point to a GitHub repository

https://github.com/researchart/fse16/

> 2) and a directory for submissions.

https://github.com/researchart/fse16/tree/master/submissions/$1

> Drag and drop your PDF onto that directory.

> Create an issue in that repository whose title is the
> XXX_YYY. Do not add any text to the comment.

Regards,
Olga & Tim
EOF
}

mkdir submissions/$1
touch submissions/$1/README.md
git add submissions/$1/README.md
git commit -am "saving"
git push origin master

txt $1 |
mail  \
 -a "From: fse2016artifacts@easychair.org" \
 -s "Registration, FSE artifacts track for $1"  \
  $2
